[package]
name = "enum-ptr"
version = "0.1.0"
authors = ["QuarticCat <QuarticCat@protonmail.com>"]
license = "MIT OR Apache-2.0"
edition = "2021"

[features]
default = ["std"]
std = []

[dependencies]
enum-ptr-derive = { version = "*", path = "../enum-ptr-derive" }
