[package]
name = "enum-pointer-derive"
version = "0.1.0"
authors = ["QuarticCat <QuarticCat@protonmail.com>"]
license = "MIT OR Apache-2.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn = { version = "1", features = ["extra-traits"]}
quote = "1"
