[package]
name = "enum-pointer-tests"
version = "0.1.0"
authors = ["QuarticCat <QuarticCat@protonmail.com>"]
license = "MIT OR Apache-2.0"
edition = "2021"
publish = false

[dependencies]
enum-pointer = { path = "../enum-pointer" }
